package entities;

// Generated May 20, 2017 9:07:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DataTakeaway generated by hbm2java
 */
@Entity
@Table(name = "data_takeaway", catalog = "db_shop_coffee")
public class DataTakeaway implements java.io.Serializable {

	private Integer takeawayId;
	private int shopId;
	private int orderId;
	private Integer customerId;
	private int staffId;
	private Date createdAt;
	private Date updatedAt;

	public DataTakeaway() {
	}

	public DataTakeaway(int shopId, int orderId, int staffId, Date createdAt,
			Date updatedAt) {
		this.shopId = shopId;
		this.orderId = orderId;
		this.staffId = staffId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public DataTakeaway(int shopId, int orderId, Integer customerId,
			int staffId, Date createdAt, Date updatedAt) {
		this.shopId = shopId;
		this.orderId = orderId;
		this.customerId = customerId;
		this.staffId = staffId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "takeaway_id", unique = true, nullable = false)
	public Integer getTakeawayId() {
		return this.takeawayId;
	}

	public void setTakeawayId(Integer takeawayId) {
		this.takeawayId = takeawayId;
	}

	@Column(name = "shop_id", nullable = false)
	public int getShopId() {
		return this.shopId;
	}

	public void setShopId(int shopId) {
		this.shopId = shopId;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "customer_id")
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "staff_id", nullable = false)
	public int getStaffId() {
		return this.staffId;
	}

	public void setStaffId(int staffId) {
		this.staffId = staffId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
