package entities;

// Generated May 20, 2017 9:07:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DataOrder generated by hbm2java
 */
@Entity
@Table(name = "data_order", catalog = "db_shop_coffee")
public class DataOrder implements java.io.Serializable {

	private Integer orderId;
	private int shopId;
	private Integer customerId;
	private Integer tableId;
	private int staffId;
	private int orderStatus;
	private Date orderDate;
	private Date orderTime;
	private float orderAmount;
	private float discount;
	private int orderType;
	private String note;
	private Date createdAt;
	private Date updatedAt;

	public DataOrder() {
	}

	public DataOrder(int shopId, int staffId, int orderStatus, Date orderDate,
			Date orderTime, float orderAmount, float discount, int orderType,
			Date createdAt, Date updatedAt) {
		this.shopId = shopId;
		this.staffId = staffId;
		this.orderStatus = orderStatus;
		this.orderDate = orderDate;
		this.orderTime = orderTime;
		this.orderAmount = orderAmount;
		this.discount = discount;
		this.orderType = orderType;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public DataOrder(int shopId, Integer customerId, Integer tableId,
			int staffId, int orderStatus, Date orderDate, Date orderTime,
			float orderAmount, float discount, int orderType, String note,
			Date createdAt, Date updatedAt) {
		this.shopId = shopId;
		this.customerId = customerId;
		this.tableId = tableId;
		this.staffId = staffId;
		this.orderStatus = orderStatus;
		this.orderDate = orderDate;
		this.orderTime = orderTime;
		this.orderAmount = orderAmount;
		this.discount = discount;
		this.orderType = orderType;
		this.note = note;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_id", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "shop_id", nullable = false)
	public int getShopId() {
		return this.shopId;
	}

	public void setShopId(int shopId) {
		this.shopId = shopId;
	}

	@Column(name = "customer_id")
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "table_id")
	public Integer getTableId() {
		return this.tableId;
	}

	public void setTableId(Integer tableId) {
		this.tableId = tableId;
	}

	@Column(name = "staff_id", nullable = false)
	public int getStaffId() {
		return this.staffId;
	}

	public void setStaffId(int staffId) {
		this.staffId = staffId;
	}

	@Column(name = "order_status", nullable = false)
	public int getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(int orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "order_date", nullable = false, length = 10)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "order_time", nullable = false, length = 8)
	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	@Column(name = "order_amount", nullable = false, precision = 12, scale = 0)
	public float getOrderAmount() {
		return this.orderAmount;
	}

	public void setOrderAmount(float orderAmount) {
		this.orderAmount = orderAmount;
	}

	@Column(name = "discount", nullable = false, precision = 12, scale = 0)
	public float getDiscount() {
		return this.discount;
	}

	public void setDiscount(float discount) {
		this.discount = discount;
	}

	@Column(name = "order_type", nullable = false)
	public int getOrderType() {
		return this.orderType;
	}

	public void setOrderType(int orderType) {
		this.orderType = orderType;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
