package entities;

// Generated May 20, 2017 9:07:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DataBill generated by hbm2java
 */
@Entity
@Table(name = "data_bill", catalog = "db_shop_coffee")
public class DataBill implements java.io.Serializable {

	private Integer billNo;
	private int shopId;
	private int orderId;
	private Date billDate;
	private Date billTime;
	private int staffId;
	private float netAmount;
	private float totalTaxAmount;
	private float totalPayAmount;
	private float discount;
	private boolean isPayed;
	private Date createdAt;
	private Date updatedAt;

	public DataBill() {
	}

	public DataBill(int shopId, int orderId, Date billDate, Date billTime,
			int staffId, float netAmount, float totalTaxAmount,
			float totalPayAmount, float discount, boolean isPayed,
			Date createdAt, Date updatedAt) {
		this.shopId = shopId;
		this.orderId = orderId;
		this.billDate = billDate;
		this.billTime = billTime;
		this.staffId = staffId;
		this.netAmount = netAmount;
		this.totalTaxAmount = totalTaxAmount;
		this.totalPayAmount = totalPayAmount;
		this.discount = discount;
		this.isPayed = isPayed;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bill_no", unique = true, nullable = false)
	public Integer getBillNo() {
		return this.billNo;
	}

	public void setBillNo(Integer billNo) {
		this.billNo = billNo;
	}

	@Column(name = "shop_id", nullable = false)
	public int getShopId() {
		return this.shopId;
	}

	public void setShopId(int shopId) {
		this.shopId = shopId;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "bill_date", nullable = false, length = 10)
	public Date getBillDate() {
		return this.billDate;
	}

	public void setBillDate(Date billDate) {
		this.billDate = billDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "bill_time", nullable = false, length = 8)
	public Date getBillTime() {
		return this.billTime;
	}

	public void setBillTime(Date billTime) {
		this.billTime = billTime;
	}

	@Column(name = "staff_id", nullable = false)
	public int getStaffId() {
		return this.staffId;
	}

	public void setStaffId(int staffId) {
		this.staffId = staffId;
	}

	@Column(name = "net_amount", nullable = false, precision = 12, scale = 0)
	public float getNetAmount() {
		return this.netAmount;
	}

	public void setNetAmount(float netAmount) {
		this.netAmount = netAmount;
	}

	@Column(name = "total_tax_amount", nullable = false, precision = 12, scale = 0)
	public float getTotalTaxAmount() {
		return this.totalTaxAmount;
	}

	public void setTotalTaxAmount(float totalTaxAmount) {
		this.totalTaxAmount = totalTaxAmount;
	}

	@Column(name = "total_pay_amount", nullable = false, precision = 12, scale = 0)
	public float getTotalPayAmount() {
		return this.totalPayAmount;
	}

	public void setTotalPayAmount(float totalPayAmount) {
		this.totalPayAmount = totalPayAmount;
	}

	@Column(name = "discount", nullable = false, precision = 12, scale = 0)
	public float getDiscount() {
		return this.discount;
	}

	public void setDiscount(float discount) {
		this.discount = discount;
	}

	@Column(name = "is_payed", nullable = false)
	public boolean isIsPayed() {
		return this.isPayed;
	}

	public void setIsPayed(boolean isPayed) {
		this.isPayed = isPayed;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
