package entities;

// Generated May 20, 2017 9:07:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DataOrderDetail generated by hbm2java
 */
@Entity
@Table(name = "data_order_detail", catalog = "db_shop_coffee")
public class DataOrderDetail implements java.io.Serializable {

	private Integer orderDetailId;
	private int orderId;
	private int menuId;
	private Integer subMenuId;
	private float orderPrice;
	private int quantity;
	private float discount;
	private String note;
	private Date createdAt;
	private Date updatedAt;

	public DataOrderDetail() {
	}

	public DataOrderDetail(int orderId, int menuId, float orderPrice,
			int quantity, float discount, Date createdAt, Date updatedAt) {
		this.orderId = orderId;
		this.menuId = menuId;
		this.orderPrice = orderPrice;
		this.quantity = quantity;
		this.discount = discount;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public DataOrderDetail(int orderId, int menuId, Integer subMenuId,
			float orderPrice, int quantity, float discount, String note,
			Date createdAt, Date updatedAt) {
		this.orderId = orderId;
		this.menuId = menuId;
		this.subMenuId = subMenuId;
		this.orderPrice = orderPrice;
		this.quantity = quantity;
		this.discount = discount;
		this.note = note;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_detail_id", unique = true, nullable = false)
	public Integer getOrderDetailId() {
		return this.orderDetailId;
	}

	public void setOrderDetailId(Integer orderDetailId) {
		this.orderDetailId = orderDetailId;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "menu_id", nullable = false)
	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	@Column(name = "sub_menu_id")
	public Integer getSubMenuId() {
		return this.subMenuId;
	}

	public void setSubMenuId(Integer subMenuId) {
		this.subMenuId = subMenuId;
	}

	@Column(name = "order_price", nullable = false, precision = 12, scale = 0)
	public float getOrderPrice() {
		return this.orderPrice;
	}

	public void setOrderPrice(float orderPrice) {
		this.orderPrice = orderPrice;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "discount", nullable = false, precision = 12, scale = 0)
	public float getDiscount() {
		return this.discount;
	}

	public void setDiscount(float discount) {
		this.discount = discount;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
